### ISSUE TITLE
Device 1189:8842 not connecting

### ISSUE THREAD

**Issue by LWooler** [rOzzy1987/MacroPad#20]
![image](https://github.com/user-attachments/assets/71fa3fce-0ed3-4340-95d4-3f1eba18a6f9)

Tried both protocols.

https://github.com/kriomant/ch57x-keyboard-tool
Appears to support the device

**Comment by jinruiting2** [comment]
Hardware ID values in Device Manager are in Hexadecimal whereas the values in config.txt are in Decimal. The converted values would be: 4489:34882

**Comment by LWooler** [comment]
ah ,thank you!!!

it is in fact working with this config
`4489:34882,mi_00,1`
